apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-ip-trace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-ip-trace
  template:
    metadata:
      labels:
        app: azure-ip-trace
    spec:
      containers:
      - name: azure-ip-trace
        image: anandbanik/ip-tracing
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 8080
          name: ip-tracing
---
apiVersion: v1
kind: Service
metadata:
  name: azure-ip-trace
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: azure-ip-trace